/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SherwoodSimpleNav {
    'leftbreak': string;
    'rightbreak': string;
    'shadowstyles': string;
  }
  interface SherwoodSimpleNavAttributes extends StencilHTMLAttributes {
    'leftbreak'?: string;
    'rightbreak'?: string;
    'shadowstyles'?: string;
  }

  interface SherwoodTriNavbar {
    'background': string;
    'breakpoint': number;
    'color': string;
    'display': string;
    'fontfamily': string;
    'fontsize': string;
    'height': string;
    'position': string;
    'styles': any;
  }
  interface SherwoodTriNavbarAttributes extends StencilHTMLAttributes {
    'background'?: string;
    'breakpoint'?: number;
    'color'?: string;
    'display'?: string;
    'fontfamily'?: string;
    'fontsize'?: string;
    'height'?: string;
    'position'?: string;
    'styles'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SherwoodSimpleNav': Components.SherwoodSimpleNav;
    'SherwoodTriNavbar': Components.SherwoodTriNavbar;
  }

  interface StencilIntrinsicElements {
    'sherwood-simple-nav': Components.SherwoodSimpleNavAttributes;
    'sherwood-tri-navbar': Components.SherwoodTriNavbarAttributes;
  }


  interface HTMLSherwoodSimpleNavElement extends Components.SherwoodSimpleNav, HTMLStencilElement {}
  var HTMLSherwoodSimpleNavElement: {
    prototype: HTMLSherwoodSimpleNavElement;
    new (): HTMLSherwoodSimpleNavElement;
  };

  interface HTMLSherwoodTriNavbarElement extends Components.SherwoodTriNavbar, HTMLStencilElement {}
  var HTMLSherwoodTriNavbarElement: {
    prototype: HTMLSherwoodTriNavbarElement;
    new (): HTMLSherwoodTriNavbarElement;
  };

  interface HTMLElementTagNameMap {
    'sherwood-simple-nav': HTMLSherwoodSimpleNavElement
    'sherwood-tri-navbar': HTMLSherwoodTriNavbarElement
  }

  interface ElementTagNameMap {
    'sherwood-simple-nav': HTMLSherwoodSimpleNavElement;
    'sherwood-tri-navbar': HTMLSherwoodTriNavbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
